# Generated by Django 4.0.4 on 2022-04-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_date', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('distance', models.PositiveIntegerField(verbose_name='Расстояние')),
            ],
        ),
    ]
